### ISSUE TITLE
Dynamic generate mutation on save

### ISSUE THREAD

**Issue by marwenDD** [maoberlehner/vuex-map-fields#124] opened 2020-11-03 13:11 UTC
Hi everyone, i’m new at vue js, and i hope i can find help hier:
we have a large App contain a very large queries and mutation and my question is :
if there any posibility to make the mutation dynamic and generated when the user change the value of v-model ? and i want just to sent the input value that has been changed, it’s possible to do that? i was searching and reading a lot but i can’t find something suitable for my problem

**this is just a part from my querie:**

```
export const GETBOBYNR = gql`
  query angebote($nr: String!, $orgNr: String!) {
    getBOByNr(pass: { token: "12345" }, nr: $nr, orgNr: $orgNr) {
      ...vDokumentDTO
      ...adresseDTO
      ...angebotDTO
      ...posList
    }

  }
  ${VDOKUMENT}
  ${ADRESSEDTO}
  ${ANGEBOTDTO}
  ${POSLIST}
`;
```

**mutation**

```
export const UPDATEBO = gql`
  mutation updateBO($id: Int!, $gueltigkeit: Int!) {
    updateBO(
      pass: { token: "12345" }
      agSet: { angebotDTO: { id: $id, gueltigkeit: $gueltigkeit }}
    )
  }
`;
```

**and this is my component:**

```
<template>
  <div>
 <v-text-field v-if="getBOByNr" v-model="getBOByNr.angebotDTO.gueltigkeit"></v-text-field>
    <v-btn class="sou-primary" @click="save()">save</v-btn>
  </div>
</template>
<script>

import { GETBOBYNR } from "../../graphql/queries/angebote/getBOByNr";
import { UPDATEBO } from "../../graphql/queries/angebote/getBOByNr";

export default {
  data() {
    return {
      name: "",
      nr: [
        "A180029",
        "A010003",
        "A010004",
        "A010005",
        "A010006",
        "A010007",
        "A010008",
        "A010010",
        "A010011",
        "A010012",
        "A010013",
      ],
    };
  },

  apollo: {
    getBOByNr: {
      query: GETBOBYNR,
      variables() {
        // Use vue reactive properties here
        return {
          nr: this.nr[0],
          orgNr: "1",
        };
      },
    },
  },

  methods: {
    save() {
      // Call to the graphql mutation
      this.$apollo
        .mutate({
          // Query
          mutation: UPDATEBO,
          // Parameters
          variables: {
            gueltigkeit: this.getBOByNr.angebotDTO.gueltigkeit,
            id: this.getBOByNr.angebotDTO.id,
          },
        })
        .then((data) => {
          // Result
          console.log(data);
        });
    },
  },
};
</script>
```

this example works using variable but actually it’s a bad idea to use variable in this case because how i said we have a huge App querie and mutation and i want to avoid sending the whole mutation inputs on save methods…

Note: my mutation return no data because i don’t need it in this case, i just want to use **mutation** to **update inputs value**.

–> all the inputs are **nested** in mutation argument in **agSet**

any suggestions or idea how to do that ?

**Comment by geoidesic** [comment] 2020-11-03 13:25
It's not clear to me from what you've written what you are trying to achieve, nor what the problem is. It's also not clear what this has to do with the `vex-map-fields` library, as you don't seem to be using it. I would suggest that you join the `vuex` discord channel and ask your question on there.

**Comment by geoidesic** [comment] 2020-11-03 13:32
I don't know what you mean by "to make the mutation dynamic and generated when the user change the value of v-model". 

Make the mutation dynamic in what way?
Mutations can be triggered when a v-model changes. It doesn't make sense to "generate" a mutation. I don't know what that would look like. I'm going to close this as I don't think this is the right place for this question.

If you are looking for more information about what this library does, I suggest you read the README and try it out.

In summary this library creates static maps between vuex state and vm root properties.
It is possible to make these maps dynamic in the sense that the component defining them can determine which node within the state they should map to, when it is created, based upon a designated vm root property containing string value... although these implementations are not part of the library at the moment, if you look through the issues you will find advice on how to do that.

Whether that meets your needs or not, I have no idea.

**Closed as completed by geoidesic** 2020-11-03 13:32 UTC
Labels: invalid

**Comment by marwenDD** [comment] 2020-11-03 13:44
Thanks for ur replay, i dont know why my issue is posted hier :( 
i dont use this library and that was not what i'm lloking for...sorry
