### ISSUE TITLE
mapFields doesn't appear to handle vuex modules correctly

### ISSUE THREAD

**Issue by MarkGStacey** [maoberlehner/vuex-map-fields#6] opened 2018-01-06 21:03 UTC
Results in error: [Vue warn]: Error in render: "TypeError: this.$store.getters[getterType] is not a function"

**Comment by maoberlehner** [comment] 2018-01-07 05:50
Hello @MarkGStacey 

are you using `namespaced: true` on your Vuex module?

**With `namespaced: true`**

```js
// SomeComponent.vue
import { createHelpers } from 'vuex-map-fields';

// `fooModule` is the name of the Vuex module.
const { mapFields } = createHelpers({
  getterType: `fooModule/getField`,
  mutationType: `fooModule/updateField`,
});

export default {
  template: `<input id="foo" v-model="foo">`,
  computed: {
    ...mapFields([
      `foo`,
    ]),
  },
};

// store/index.js
new Vuex.Store({
  // ...
  modules: {
    fooModule: {
      namespaced: true,
      state: {
        form: { foo: `` },
      },
      // `getField` and `updateField` must be added in the module.
      getters: {
        getField,
      },
      mutations: {
        updateField,
      },
    },
  },
});
```

**Without namespaces**

```js
// SomeComponent.vue
import { createHelpers } from 'vuex-map-fields';

// If you do not use namespaces you most likely
// want to rename the getter and mutation helpers
// because otherwise you cant reuse them in multiple,
// non namespaced modules.
const { mapFields } = createHelpers({
  getterType: `getFooField`,
  mutationType: `updateFooField`,
});

export default {
  template: `<input id="foo" v-model="foo">`,
  computed: {
    ...mapFields([
      `foo`,
    ]),
  },
};

// store/index.js
const { getFooField, updateFooField } = createHelpers({
  getterType: `getFooField`,
  mutationType: `updateFooField`,
});

new Vuex.Store({
  // ...
  modules: {
    fooModule: {
      state: {
        form: { foo: `` },
      },
      getters: {
        getFooField,
      },
      mutations: {
        updateFooField,
      },
    },
  },
});
```

Let me know if this worked for you. I'll add those examples to the README. Thanks for submitting this issue.

**Comment by maoberlehner** [comment] 2018-01-27 10:07
I'm closing this, because as far as I'm aware, everything works as expected. Please reopen this issue or create a new one if you have problems making it work, thanks.

**Closed by maoberlehner** 2018-01-27 10:07 UTC

**Comment by kjfdebruin** [comment] 2018-09-14 11:28
I forgot `namespaced: true` and also got the above error. I can confirm that modules are handled correctly and that mapFields works. Thanks @maoberlehner for a great library!
