### ISSUE TITLE
How to specify namespace for mapFields through component props

### ISSUE THREAD

**Issue by max-frai** [maoberlehner/vuex-map-fields#51] opened 2019-02-22 18:34 UTC
I want to pass `namespace` from vuex module with `props` but it seems to be impossible.

    <my-component namespace="ns1" />

    // my-component code
    export default {
      props: ["namespace"],
      computed: {
        ...mapFields(??this.namespace??, ["attr1", "attr2"])
      }
    }

Of course, there is no way to use `this` in such way so we don't have access to props. How can I specify namespace as prop in such case?

**Comment by max-frai** [comment] 2019-02-22 19:42
I found a dirty workaround. I rewrote method `mapFields` and calculate `getterType` in runtime:
```
    const field = {
      get() {
        var getterType = `${this.namespace}/getField`;
        return this.$store.getters[getterType](path);
      },
      set(value) {
        var getterType = `${this.namespace}/setField`;
        this.$store.commit(mutationType, { path, value });
      }
    };
```
Of course, this required `namespace` to be declared. I understand this is dirt and not for general usage, but maybe it's possible to rewrite `mapFields` with such functionality?

**Comment by max-frai** [comment] 2019-02-22 20:57
If it's okay, I can write pull request modifying `mapFields` with ability to specify inner prop name that we should use  in runtime for namespace calculating.

**Comment by maoberlehner** [comment] 2019-02-23 05:00
Hey @max-frai! Thank you for your input. If I understand it correctly, this is a duplicate of https://github.com/maoberlehner/vuex-map-fields/issues/24, please use the existing issue for further discussion (if it is no duplicate, please let me know and I'll reopen this issue).

I'll consider accepting a pull request if it can be done in a backwards compatible manner and I'm happy with the resulting API.

Thank you for contributing!

**Closed by maoberlehner** 2019-02-23 05:00 UTC
Labels: duplicate
